In [1]:
import numpy as np
import pandas as pd
import assets.script as script
from sklearn.linear_model import LinearRegression
from sklearn.naive_bayes import GaussianNB

### Example `script.py` Use

In [8]:
x = [np.random.randn(10) for i in range(100)]
y = np.random.randint(1, 100, 100)

In [9]:
df = pd.DataFrame(x, columns=['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine'])
df = df.join(pd.Series(y, name='target'))

In [10]:
X_train, X_test, y_train, y_test = script.split_data(df, target='target')


No columns dropped.

Target values: [21 62 61 76 13 52 59 94 82 52 78 27 10 20 33 40 77 64 51  5 88 94 10 68
 89 65 50 94 80 76  1 41 74 56 80  5 19  7 25 65 63 53 26 16 94 85 99 93
 11 80 37 23 77 88 68 29 34 39 49 20 28 13 22 54 70 33 21 55 40 71 66  7
 54 96 79 47 33 40 66 94 11 22 48 66 43 95 45 49 36 47 73 68 94 84 59 53
 65 98 84 94] 

Column(s) remaining: Index(['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight',
       'nine', 'target'],
      dtype='object')

Data is unscaled.
training sample size:  80
testing sample size:  20


In [5]:
y_pred, y_prob = script.get_predictions(GaussianNB(), X_train, y_train, X_test)

In [6]:
print(y_pred)
print(len(y_pred))

[78 15 35 35 93 35 35  9 55 35 87 29 35 55 87 88 35 35 88 55]
20


In [7]:
script.print_scores(y_test, y_pred, y_prob)

Confusion matrix:
 [[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 

/opt/homebrew/Caskroom/miniforge/base/envs/lighthouse/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/Caskroom/miniforge/base/envs/lighthouse/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
query = """
SELECT * FROM flights
LIMIT 200
"""

script.make_csv(query, 'test_lee.csv')

exists


fl_date mkt_unique_carrier branded_code_share mkt_carrier  \
0    2018-01-07                 DL                 DL          DL   
1    2018-01-07                 DL                 DL          DL   
2    2018-01-07                 DL                 DL          DL   
3    2018-01-07                 DL                 DL          DL   
4    2018-01-07                 DL                 DL          DL   
..          ...                ...                ...         ...   
195  2018-01-07                 DL                 DL          DL   
196  2018-01-07                 DL                 DL          DL   
197  2018-01-07                 DL                 DL          DL   
198  2018-01-07                 DL                 DL          DL   
199  2018-01-07                 DL                 DL          DL   

     mkt_carrier_fl_num op_unique_carrier tail_num  op_carrier_fl_num  \
0                  1521                DL   N811DZ               1521   
1                  1522                DL   N964DN               1522   
2                  1523                DL   N340NB               1523   
3                  1524                DL   N948AT               1524   
4                  1525                DL   N963DN               1525   
..                  ...               ...      ...                ...   
195                1699                DL   N152DL               1699   
196                1700                DL   N319DN               1700   
197                1701                DL    N6709               1701   
198                1702                DL   N362NW               1702   
199                1703                DL   N816DN               1703   

     origin_airport_id origin  ... distance  carrier_delay weather_delay  \
0                13485    MSN  ...    311.0            NaN           NaN   
1                14730    SDF  ...    321.0          204.0           0.0   
2                10721    BOS  ...    632.0            NaN           NaN   
3                13487    MSP  ...    596.0            NaN           NaN   
4                13487    MSP  ...   1501.0            NaN           NaN   
..                 ...    ...  ...      ...            ...           ...   
195              14869    SLC  ...   2935.0            NaN           NaN   
196              10721    BOS  ...    946.0            NaN           NaN   
197              10397    ATL  ...   1747.0            NaN           NaN   
198              12953    LGA  ...   1076.0            NaN           NaN   
199              11433    DTW  ...    983.0            NaN           NaN   

    nas_delay  security_delay  late_aircraft_delay  first_dep_time  \
0         NaN             NaN                  NaN             NaN   
1         0.0             0.0                  0.0             NaN   
2         NaN             NaN                  NaN             NaN   
3         NaN             NaN                  NaN             NaN   
4         NaN             NaN                  NaN             NaN   
..        ...             ...                  ...             ...   
195       NaN             NaN                  NaN             NaN   
196       NaN             NaN                  NaN             NaN   
197       NaN             NaN                  NaN             NaN   
198       NaN             NaN                  NaN             NaN   
199       NaN             NaN                  NaN             NaN   

     total_add_gtime  longest_add_gtime  no_name  
0                NaN                NaN      NaN  
1                NaN                NaN      NaN  
2                NaN                NaN      NaN  
3                NaN                NaN      NaN  
4                NaN                NaN      NaN  
..               ...                ...      ...  
195              NaN                NaN      NaN  
196              NaN                NaN      NaN  
197              NaN                NaN      NaN  
198              NaN                Na

# Gathering Data